import type { Metadata } from "next";
import { Nunito_Sans } from 'next/font/google';
import localFont from "next/font/local";
import "./globals.css";


// Initialize Nunito Sans with the weights you need
const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  // Optional: you can add display: 'swap' for better performance
  display: 'swap',
  variable: '--font-nunito-sans', // This creates a CSS variable
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Strentor Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-pink-500/20 via-purple-600/20 to-blue-700/20`}
      > */}
       <body
        className={`${nunitoSans.className} antialiased bg-gradient-to-r from-pink-500/20 via-purple-600/20 to-blue-700/20`}
      >
        {children}
      </body>
    </html>
  );
}
